### ISSUE TITLE
Include uniform types on shaderMaterial's returned class type

### ISSUE THREAD

**Issue by mattrossman** [pmndrs/drei-vanilla#23]
### Describe the feature you'd like:

`shaderMaterial()` has trouble with TypeScript. The storybook example has several type errors because custom uniforms don't exist on the resulting class type.

<img width="863" alt="image" src="https://github.com/pmndrs/drei-vanilla/assets/22670878/a1b0ad0f-3235-4485-80e0-bf9e0822ffaf">

In the main drei project, they work around this by specifying the types when extending the JSX namespace. 

https://github.com/pmndrs/drei/blob/f5354c4cc5349e048c00d5ad2b8c839cde5bd132/.storybook/stories/shaderMaterial.stories.tsx#L58-L69

This adds friction and duplication in userland though. I would like `shaderMaterial` to automaticallly wire up these uniform types to its resulting class type. Uniform types can be inferred from the function arguments or provided by the user through generics.

### Suggested implementation:

See implementation with generics here: [TypeScript Playground](https://www.typescriptlang.org/play?target=7#code/JYWwDg9gTgLgBAKjgQwM5wCoAkBKBRPOAMyghDgHIYALKAUzooG44B6VuGATzDtQC44ABgB0ARgCsAZhFCAsAChFrBAkWI4AETwBZAPJwAtHGAA7InSj0AJnACup4EWjluvVOoStFigMYRTVHgdZBhLYGQAGzE4AF44VGpka0sQsKgIyIAKdTgAb05QOkEhOABfABpcgAMAHgA1PBwMPAANAH0AZSwAQW0cAD5qqoU4ODqAMRwegHEdPAA5DC7e-qGRgEofBX9A+BBQ8KiY+NM6AHc4NKPorK2FA-TMsREYItyxz-Y4AD0Afm2ylUni0ugMxjoAA8wJFgL5gPAHE4XJweHxPN4lDsAkErocMlEAExxBJJFJQa4EyK1PIHMCCbD4PAiDBQmB2ehwAA+cFMdkikTKAxyo3ycDpgj5AvKIzGdUazTaKz6TXWNVqU1m8yWyrWw0U9z8OP2+MyxNOFzxTyJd0UjxuhJEdI+nzYHH+23tVMddJJZ0ujIIIk0oWQrMh7Potqx2xUalGSAAkjoAAoAGV0iwwPQwib0Cwx2zcdDgAFVHM4oCB6lE7CXYrkeYHmQBhOwAIzo4cjdEbmFwQe7HN7op5idMMCkhJ6VmQXD7E0iEFCU5nUDnfebIjSGUhABZNwPmTvgJCpIemSIAIp2fGOAIXoP1Oi+GDQA+j-uX5+v6Dnz9bj+b5QISj6thAS5QH2fIgJ2UGfu2EAQXQyCmH2a5zrUqFcAM0H8pETBFmiZYVi4qCdEkvAkgUADapjICAxQJDAGSmAA5gAuoI5bIlWNaRHW5SEVixZwBRySpKaUTjkEqG+HQtQYDxlYgOgbJ0KY1joMpZHibwAwklu4nkpSmRwAAZJgOlVqgwmicZknWpEKbIOujHpKginWapcDqZp2mkTZel0AZ8RGWSjk3C5bl0B5FlwNFbxRF5gWqQMdnEQ5FJSdSSmpWpEYaVpJG8apwWhbkWT+nAWRgK5DGxZYqB-IIWWmVE0UNR5KWlagAwbHEBltTlMkwHJCl5b1-XxQUADWdBcIIQSsWxQnbFCkCwMQDivsAASkhJ2VOT1KkFWE-klad5UimMSKnQy3moLKcAAG6WGEkJZUtLFmGxz0kMgbGMROX3MStz0BOOCItTVXqZK1EVHTco3jSdZHTbEBkvRAwDWAa+S5KJj14NCqEpLY8S0fNXAmKYcDUxARBWflXFii9tZMZNp00dTHHlEJbq8nwMDoOzAl8PYmmWHAABEYt1jL9MLdsYy7LiGk-RL8R6O2ABWL4wCIGsZHwWR3WRGzCarxqS71JN1VLFNwDr+uviIJBkHgE4m6gWTG8AfBOsgYBZFkdENRUr0cxxA2Y3A4eMZHBTyyWZQxwNaCXWR9tk3Q1jCbkviRGg6DtZEvmFRd4WHWXBOimMslvL4Ss02FR7bqE1Clm8kSoCIbEaZYhylqWiaaHcBf13AassXYv5QLV9XuU1MPDU5nXL1Anlc+jA15C6Dd2LwC8FCIZ91TFHmR+bNmCDfqk547kdvbAUJZZHANAxrWXlJbKuusQaANUZ7x3ooxPmjNfLewDqgPeB9PguwNiIFIRAzB0BTKQY+3Asg0GAE9XkEc64AIAQPGAgg7iDU4NQPBIh76oATnQDiIgU7PWIQ3WK5CXqxwMjg6hfc6EMKYSnEkXDWEALKH-KeYwyj-1dIgt2JdgBsVMLwvBkcL5dSapI+BkNHAwD+CIVR6BM4OFmqYCA5w6aZzXsjPYqMd42X6lbT4MjRSuNyPQSMdNa7WMRmXNGjjhKuKAA)

<img width="686" alt="image" src="https://github.com/pmndrs/drei-vanilla/assets/22670878/b8f2ce3e-7c5c-4ed0-aeaa-9591c945662f">

 

This resolves the type errors in the storybook example.

I can make a PR for this.

**Comment by mattrossman** [comment]
Updated implementation with uniform types for `.setValues()`

[Playground Link](https://www.typescriptlang.org/play?target=7#code/JYWwDg9gTgLgBAKjgQwM5wCoAkBKBRPOAMyghDgHIYALKAUzooG44B6VuGATzDtQC44ABgB0ARgCsAZhFCAsAChFrBAkWI4AETwBZAPJwAtHGAA7InSj0AJnACup4EWjluvVOoStFigMYRTVHgdZBhLYGQAGzE4AF44VGpka0sQsKgIyIAKdTgAb05QOkEhOABfABpcgAMAHgA1PBwMPAANAH0AZSwAQW0cAD5qqoU4ODqAMRwegHEdPAA5DC7e-qGRgEofBX9A+BBQ8KiY+NM6AHc4NKPorK2FA-TMsREYItyxz-Y4AD0Afm2ylUni0ugMxjoAA8wJFgL5gPAHE4XJweHxPN4lDsAkErocMlEAExxBJJFJQa4EyK1PIHMCCbD4PAiDBQmB2ehwAA+cFMdkikTKAxyo3ycDpgj5AvKIzGdUazTaKz6TXWNVqU1m8yWyrWw0U9z8OP2+MyxNOFzxTyJd0UjxuhJEdI+nzYHH+23tVMddJJZ0ujIIIk0oWQrMh7PotoepqJIlQdBg9Sidj4WTyuQlvMtgeZIZgYbZHLo0bKhqxQLUoyQAEkdAAFAAyukWGB6GBregWGO2bjocAAqo5nFAQMnIqm4rkebmRABhOwAIzo4cjdGnmFwQdXxY3NdMMCkhJ6VmQXA3E0iEFCR5PUDPG9naQykIALI+t8zn8BIVIP0yRAARTsfFHACf8g3qOhfBgaB31FGdPxEKCYOgP8EM3ACUNgqBCQg5k5wgK8oA3PkQGXEiMMXCAiLoZBTA3O8z1qeiuAGUj+UiJhezRQdhxcVBOiSXgSQKABtUxkBAYoEhgDJTAAcwAXUEIdkVHcdJzKbisT7OAhOSVJY0ifcgno3w6FqDA1JHEB0DZOhTGsdAbIEgzeAGElcms-jR3QAAyXI9BABErKQgzyUpTIKjgAAiBMkxTPhYs8wLRQKBLNL4QQsjAZB72k9IBH0skjOtSJ63yqTE0sVArNcvyBg2OJPIANwgYBbG0xQ9IisqbkqgqaqgOqfPUuy4AcpyXN8uz3LoTz4lnPqKWMwbqqKuB-LgQa3iierZtQAYdN60rVvKg7xvsiNHOcvirvmxbciyf04FyqrCtqv5BBWqKonWz6Rsu2yjua2JPN+4zTILUwLOBgSmq2sUAGs6C4QQgnkhTyh0xQoUgWBiAcGDgACUlDPOm54b8yabum+6QcekUxiREGGQauzZTgVrLDCSEVoxuSzAUrmSGQBTpIPAXZKxrmAn3BFvrer1Mh+s6-pMvZzMssaQcR8HuY66wDXyXI9I51A8GheiUlseJxNRrgTFMOBHYgIhMAtlSxVapL2cOsTHaU8ocbdbMgnQX2Jz4ewnMsOKo9TWLXbR7Yxl2XFHKFmP4j0RcACtoJgEQs4yNNWYEjYdPT41Y6uq28rju24DzwuYJEEgyDwA8y9QLJS+APgnWQMAsiyCTqpixO6CUsHPIn6SYoKafyln5q0AZgSG5tuhrFx0VfEiNB0A12mwnp5b1eM03RTGMy3l8FOnaWpC0moAc3kiVARAUxzLEOAcA4ayaDuPvV0Gc5J2FQlAd6Q0ipK0huVAGw1RoW0RhmW+nxUB2F4DAgoIgCF5TgbVGKFc-KCDIXZbeTcp68yhCtGKYsJZZxWuUKuadXTEGgG9CBcAF4zzgO7SaPdB6oGahgzhnxW5FxECkIgZg6D1lILg7gWQaDAFQDFSSi8b6SNdL-GAOU56cGoBokQlDUD8KUiIaeXM9EJETDlVqxi1GmO-hYqxNikokmcXYzhZZq7+I4a6aR7dj7AAUqYVxGiYpEI2rVdhWJJHy0cDAP4IhonoA3g4ZGpgIDnBdhvRBNxoba2pnZJqgSxhlFyDUpJcB6CRhdqfIpV8Lq6wRjpOpQA)

**Comment by vis-prime** [comment]
Oh yes ! , many effects use `shaderMaterial` and they all have this problem , would be great to have a proper solution 



if you can, do make the PR ❤
