### ISSUE TITLE
Transmitting objects cannot see other transmitting objects

### ISSUE THREAD

**Issue by coincoc** [pmndrs/drei-vanilla#58]
Hi , The following image shows the effect in Codesandbox,It cannot see other transparent objects

![微信图片_20240321105940](https://github.com/pmndrs/drei-vanilla/assets/67940946/1c37895d-2caa-42ef-b194-ab93543fca11)

**Comment by vis-prime** [comment]
you need to create unique FBO/webglRendertarget for each mesh

share the sandbox , i'll edit it

I'll add a storybook example later

**Comment by coincoc** [comment]
> you need to create unique FBO/webglRendertarget for each mesh您需要为每个网格创建唯一的 FBO/webglRendertarget
> 
> share the sandbox , i'll edit it共享沙盒，我会编辑它
> 
> I'll add a storybook example later我稍后会添加一个故事书示例

Sorry for the late reply. I'll try what you said. Thanks
